name: Terakoya Deploy
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-20.04
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
 
      - name: Install Dependencies
        run: npm install
 
      - name: Build
        run: npm run build
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist